added account id because was getting this errror
Run aws-nuke --config ./.github/workflows/cleanup/aws-nuke-config.yml --no-dry-run --force --force-sleep 3 --max-wait-retries 100 --access-key-id *** --secret-access-key ***
  aws-nuke --config ./.github/workflows/cleanup/aws-nuke-config.yml --no-dry-run --force --force-sleep 3 --max-wait-retries 100 --access-key-id *** --secret-access-key ***
  shell: sh -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Your account ID '400803493251' isn't listed in the config. Aborting.
aws-nuke version v2.25.0.31.g10a0b49 - Sun Sep 22 03:22:16 UTC 2024 - 10a0b49a4b1ed69909b8eb70f5ba32648dd2b830